create missing directories

diff --git a/etc/push-updates b/etc/push-updates
--- a/etc/push-updates
+++ b/etc/push-updates
@@ -21,6 +21,8 @@ while read source; do
         fi
     fi
     echo "copy ./${source} -> ${target} ($user)"
-    rsync -avh --partial --progress "$source" "$target" && \
+    rsync -avh --partial --progress \
+          --rsync-path "mkdir -p ${target%/*} && rsync" \
+          "$source" "$target" || { echo "operation failed"; exit 1; }
     chown -R "$user:$group" "${target}"
 done < <(git ls-tree --name-only -r HEAD)
diff --git a/etc/push-updates-home-single-user b/etc/push-updates-home-single-user
--- a/etc/push-updates-home-single-user
+++ b/etc/push-updates-home-single-user
@@ -23,5 +23,7 @@ while read source; do
     esac
 
     echo "copy ./${source} -> ${target}"
-    rsync -avh --partial --progress "$source" "$target"
+    rsync -avh --partial --progress \
+          --rsync-path "mkdir -p ${target%/*} && rsync" \
+          "$source" "$target" || { echo "operation failed"; exit 1; }
 done < <(git ls-tree --name-only -r HEAD)
