add advanced ssl script

diff --git a/etc/skel.obi/.bashrc.d/all/basic b/etc/skel.obi/.bashrc.d/all/basic
--- a/etc/skel.obi/.bashrc.d/all/basic
+++ b/etc/skel.obi/.bashrc.d/all/basic
@@ -67,14 +67,83 @@ alias systemd-show-runlevel='systemctl list-units --type=target'
 # log colorizer
 alias ccze='ccze -A'
 
-o_ssl_cert_hash(){
+o_adm_ssl_cert_hash(){
     local cfile="$1"
     ln -s "$cfile" "$(openssl x509 -hash -noout -in "$cfile").0"
 }
 
-o_ssl_cert_decode(){
+o_adm_ssl_cert_hash_adv(){
+	#program [-f] /path/to/certfile
+	local openssl=/usr/bin/openssl
+	local certdir=${SSL_CERT_DIR:-/etc/ssl/certs}
+
+	# -f as firt args sets overwrite mode
+	if [[ "$1" = "-f" ]]; then
+	   local overwrite=1
+	   shift # remove $1
+	fi
+
+	if [ ! -f $openssl ]; then
+	  	echo "ERROR: Can't find $openssl. openssl-util installed?" >&2
+	fi
+
+
+	if [ -f "$1" ]; then
+	  	local certfile=$1
+	  	local certname="$(basename "$certfile")"
+
+	  	echo "Certificate $certname"
+	  	echo "  copy to $certdir"
+
+		if (( $overwrite == 1 )) && [[ -f "$certdir/$certname" ]]; then
+		    echo >&2
+		    echo "ERROR: certificate $certname exists" >&2
+		    exit 2;
+		fi
+
+		cp "$1" "$certdir/$certname"
+
+		# create symbolic link from hash
+		echo -n "  generating hash: "
+		local HASH="$($openssl x509 -hash -noout -in "$certfile")"
+		echo "$HASH"
+
+		# handle hash collisions
+		suffix=0
+		while (( $overwrite == 1 )) && [ -h "$certdir/$HASH.$suffix" ]; do
+			(( foo++ ))
+		done
+
+		echo "  linking $HASH.$suffix -> $certname"
+
+		if [[ $overwrite ]]; then
+			ln -sf "$certname" "$certdir/$HASH.$suffix"
+		else
+			ln -s "$certname" "$certdir/$HASH.$suffix"
+		fi
+	else
+		echo >&2
+		echo "ERROR: file does not exist $1" >&2
+		echo >&2
+		echo "This script adds (root) certificates for wget(ssl) to $certdir." >&2
+		echo "SYNTAX: $(basename $0) [Options] [x509-certificate]" >&2
+		echo >&2
+		echo "Option: -f      force overwriting if certificate exists" >&2
+	fi
+}
+
+o_adm_ssl_cert_decode(){
     local cfile="$1"
     openssl x509 -in "$cfile" -text -noout
+}
+
+o_adm_sort_passwd(){
+    if sort -n -t: -k3 < /etc/passwd >/etc/passwd.new; then
+        cp /etc/passwd /etc/passwd.old
+        mv /etc/passwd.new /etc/passwd
+    else
+        echo "sorting of passwd failed"
+    fi
 }
 
 o_ping_fragmentation_mtu_ip(){
